server:
   port: 8080

management:
   endpoint:
      health:
         show-details: always
      metrics:
         enabled: false
      prometheus:
         enabled: true
   metrics: 
      export:
         prometheus:
            enabled: true
         enabled: false
   endpoints: 
      web:
         exposure:
            include: '*'
  
            
spring:
   application: 
      name: calc
   cloud:
       consul:
          discovery:
             instanceId: ${spring.application.name}:${random.value}
             
